### ISSUE TITLE
非湖北电信网络是否可用?

### ISSUE THREAD

**Issue by M1s4k1** [sht2017/iptv#1]
尝试逆向上海联通iptv的认证过程
发现有一段是在获取EncryToken之后, 计算得出Authenticator. 没有找到具体的加密过程

对于这个场景,当前项目是否可用?

**Comment by sht2017** [comment]
参考 [/epg/authenticator.py](https://github.com/sht2017/iptv/blob/main/src/epg/authenticator.py)
用给定的鉴权信息和plain/md5算然后对比authenticator是否一致 如果不一致则尝试使用[/src/epg/utils.py](https://github.com/sht2017/iptv/blob/main/src/epg/utils.py)穷举盐 若穷举不出或盐不正确可能采用了其他算法

**Comment by sht2017** [comment]
from epg.credential import Credential
credential = Credential(...) #参见模块的docstring
authenticator = Authenticator(
    credential = credential,
    auth_method = AuthMethod.PLAIN, #这里是算法
)
authenticator.info即为结果

**Comment by sht2017** [comment]
解决了吗 或者还有什么疑问吗

**Comment by sht2017** [comment]
之后有后续或者类似使用上的问题可以发到discussions里

**Comment by M1s4k1** [comment]
> 参考 [/epg/authenticator.py](https://github.com/sht2017/iptv/blob/main/src/epg/authenticator.py) 用给定的鉴权信息和plain/md5算然后对比authenticator是否一致 如果不一致则尝试使用[/src/epg/utils.py](https://github.com/sht2017/iptv/blob/main/src/epg/utils.py)穷举盐 若穷举不出或盐不正确可能采用了其他算法

sorry,回复晚了. 项目中的加密未能使用. 反编译了从abd提取机顶盒的apk后,获取了加密流程. 有人需要的话可以留言. 我会提供脚本

**Comment by sht2017** [comment]
> > 参考 [/epg/authenticator.py](https://github.com/sht2017/iptv/blob/main/src/epg/authenticator.py) 用给定的鉴权信息和plain/md5算然后对比authenticator是否一致 如果不一致则尝试使用[/src/epg/utils.py](https://github.com/sht2017/iptv/blob/main/src/epg/utils.py)穷举盐 若穷举不出或盐不正确可能采用了其他算法
> 
> sorry,回复晚了. 项目中的加密未能使用. 反编译了从abd提取机顶盒的apk后,获取了加密流程. 有人需要的话可以留言. 我会提供脚本

很好奇你这边的算法是什么 有其他联系方式可以交流一下吗

**Comment by M1s4k1** [comment]
emmm 加个wx?base64(TTFzNGsxeHl6)
